"""Models for the Mission Planner module."""

from datetime import datetime

from pydantic import BaseModel, Field

from backend.models.enums import SeverityLevel
from backend.models.shared import GraniteAttribution


class MissionPhase(BaseModel):
    """A phase within a mission timeline."""

    id: str = Field(..., description="Unique phase identifier")
    name: str = Field(..., description="Phase name (e.g., Pre-Launch, Ascent, Orbit)")
    start_time: datetime = Field(..., description="Phase start time")
    end_time: datetime = Field(..., description="Phase end time")
    description: str = Field(default="", description="Phase description")
    safety_margin_hours: float = Field(
        default=0.0, ge=0.0, description="Safety time margin in hours"
    )
    dependencies: list[str] = Field(
        default_factory=list, description="IDs of prerequisite phases"
    )


class MissionTimeline(BaseModel):
    """Complete mission timeline with phases."""

    mission_id: str = Field(..., description="Mission identifier")
    phases: list[MissionPhase] = Field(
        default_factory=list, description="Ordered mission phases"
    )
    total_duration_hours: float = Field(
        ..., ge=0.0, description="Total mission duration in hours"
    )
    critical_path: list[str] = Field(
        default_factory=list, description="Phase IDs on the critical path"
    )


class MissionParameters(BaseModel):
    """Input parameters for mission planning."""

    mission_name: str = Field(..., description="Name of the mission")
    vehicle: str = Field(..., description="Vehicle/spacecraft for the mission")
    crew_size: int = Field(default=0, ge=0, description="Number of crew members")
    destination: str = Field(..., description="Mission destination")
    launch_window_start: datetime = Field(..., description="Launch window opening")
    launch_window_end: datetime = Field(..., description="Launch window closing")
    objectives: list[str] = Field(
        default_factory=list, description="Mission objectives"
    )
    constraints: list[str] = Field(
        default_factory=list, description="Mission constraints"
    )


class ResourceConflict(BaseModel):
    """A detected resource or scheduling conflict."""

    id: str = Field(..., description="Unique conflict identifier")
    type: str = Field(
        ..., description="Conflict type (e.g., schedule, resource, crew)"
    )
    description: str = Field(..., description="Description of the conflict")
    severity: SeverityLevel = Field(..., description="Conflict severity")
    affected_phases: list[str] = Field(
        default_factory=list, description="Phase IDs affected by this conflict"
    )
    resolution_options: list[str] = Field(
        default_factory=list, description="Possible resolutions"
    )


class PreFlightChecklist(BaseModel):
    """Pre-flight readiness checklist generated by AI."""

    mission_id: str = Field(..., description="Mission identifier")
    items: list[dict] = Field(
        default_factory=list,
        description="Checklist items with status and requirements",
    )
    overall_readiness: float = Field(
        ..., ge=0.0, le=1.0, description="Overall readiness score"
    )
    blockers: list[str] = Field(
        default_factory=list, description="Items blocking launch readiness"
    )
    recommendation: str = Field(..., description="AI-generated readiness recommendation")
    attribution: GraniteAttribution = Field(..., description="AI attribution metadata")
    generated_at: datetime = Field(
        default_factory=datetime.utcnow, description="Checklist generation timestamp"
    )
